backend/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('<int:pk>/index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/change/', views.change, name='change'),
    path('list/', views.list, name='list'),
    path('<int:pk>/user_page/', views.user_page, name='user_page'),
    path('', views.login, name='login'),
]

backend/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

backend/core/models.py
from django.db import models

# Create your models here.

backend/core/forms.py
from django import forms

class UserForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)

backend/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from .forms import UserForm, LoginForm

# Create your views here.

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(
                username = username,
                password = password,
            )
            if user is not None:
                return redirect('core:index', user.pk)
        return redirect('core:login')
    else:
        form = LoginForm(request.POST)

    content = {'form': form}

    return render(request, 'core/login.html', content)

def index(request, pk):
    user = User.objects.get(pk=pk)
    content = {
        'pk': pk,
        'username': user.username
    }
    return render(request, 'core/index.html', content)

def create(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.create_user(
                username=username,
                password=password
            )
            user.save()
            return redirect('index')
    else:
        form = UserForm()
    context = {'form': form}

    return render(request, 'core/create.html', context)

def list(request):
    users = User.objects.all()

    return render(request, 'core/list.html', {'users': users})

def change(request, pk):

    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.get(pk=pk)
            user.set_password(password)
            user.save()
            return redirect('index', pk)
    else:
        user = User.objects.get(pk=pk)
        form = UserForm(initial={'username': user.username})
    context = {'form': form, 'pk': pk}

    return render(request, 'core/change.html', context)

def user_page(request, pk):
    content = {'content': 'Success', 'pk': pk}
    return render(request, 'core/user_page.html', content)

backend/core/templates/core/change.html
<form action="{% url 'change' pk %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="change"/>
</form>

backend/core/templates/core/create.html
<form action="{% url 'core:create' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="create"/>
</form>

backend/core/templates/core/index.html
<h1>{{ username }}</h1>
<ul>
    <li>
        <a href="{% url 'core:create' %}">Create</a>
    </li>
    <li>
        <a href="{% url 'core:list' %}">List</a>
    </li>
    <li>
        <a href="{% url 'core:user_page' pk %}">User page</a>
    </li>
</ul>
</br>

backend/core/templates/core/list.html
<ul>
    {% for user in users %}
        <li><a href="{% url 'core:change' user.id %}">{{user}}</a></li>
    {% endfor %}
</ul>

backend/core/templates/core/login.html
<form action="{% url 'core:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="login"/>
</form>

backend/core/templates/core/user_page.html
{{ content }}
</br>
<a href="{% url 'core:index' pk %}">back</a>